Player.create(nickname: "Matador")
Player.create(nickname: "Wizard")
Player.create(nickname: "Jenga")
Player.create(nickname: "Chef")
Player.create(nickname: "Admiral")
Player.create(nickname: "Banana")
Player.create(nickname: "Dragon")
Player.create(nickname: "Captain Planet")
Player.create(nickname: "Coozie")
Player.create(nickname: "Chompy")
Player.create(nickname: "Big Kahuna")

Weapon.create(name: "Assassin Star Loaded Bicycle")
Weapon.create(name: "Wood Blocks")
Weapon.create(name: "Milk Filled Udders")
Weapon.create(name: "A Jurassic Snaggletooth")
Weapon.create(name: "Beer")
Weapon.create(name: "Pollution")
Weapon.create(name: "Strainer")
Weapon.create(name: "Broken Wand")
Weapon.create(name: "Scooter")
Weapon.create(name: "Fire")


